baseURL = "http://jiaoluo.mycloudice.com/"
languageCode = "en-us"
title = "角落"
themesDir = "themes"
theme = "hugo-hero-theme"
publishDir = "docs"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "角落：针对人生疑惑问答的App"
    meta_og_title = "角落App"
    meta_og_type = "website"
    meta_og_url = "http://jiaoluo.mycloudice.com/"
    meta_og_description = "让懂你的人，为你的迷茫解答"

[[menu.main]]
    name = "联系方式"
    url = "/contact/"
    weight = 4

[[menu.main]]
    name = "隐私政策"
    url = "/privacy/"
    weight = 5

[[menu.main]]
    name = "合约条款"
    url = "/terms/"
    weight = 6

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
